### ISSUE TITLE
It would be cool of you add an ability to compress multiple video files at once

### ISSUE THREAD

**Issue by dqhieu** [dqhieu/CompressXApp#31]
https://x.com/EldarGezalov/status/1732775841959120928?s=20

Twitter DM

**Comment by flutterrausch** [comment]
2nd this, came here right after buying. I have e.g. dagoberts twitter course on disk (which is unreasonably high quality), and would like to compressX the

- whole folder at once.
- Queuing multiple drag&drop files would also be nice.

**Comment by dqhieu** [comment]
> Btw, I have some suggestions for the batch processing of the video, I think drag and dragging the folder would be nice simple UI, and would be nice to have the place where we can specify the output file names like using {tag} so that we can specify the batch exported file easy to recognize :) like the Output file name from this UI
