### ISSUE TITLE
Unable to update the app to 1.1

### ISSUE THREAD

**Issue by Johanncc01** [dqhieu/CompressXApp#47]
Hi, 
When I try to update the app, I get this error code. My current version is 1.0.1 and the download link doesn't redirect to the latest version of the app, so I'm unable to update. 

Is there a workaround for this? Or even a download link for version 1.1 ?

Thanks a lot !

<img width="824" alt="d08bdcbc06a55dd6eebaff92674ca956d9223ea59820eb3dc3df3d33c7cc50a5" src="https://github.com/dqhieu/CompressXApp/assets/101647118/3219816b-fcd1-4d4d-926c-9fc80d3e214b">

**Comment by dqhieu** [comment]
Hi @Johanncc01 , could you help to go to Lemon Squeezy and download the latest version?

**Comment by Johanncc01** [comment]
Hi @dqhieu, I just got back to Lemon Squeezy and the latest version was there! I dont know if the inital bug was fixed, but I was able to update so I'll close this issue.

**Comment by Johanncc01** [comment]
As a follow up, this popped up when I searched for updates on v1.1 😅
<img width="372" alt="image" src="https://github.com/dqhieu/CompressXApp/assets/101647118/ae1e7e62-ae25-4999-bcdd-5705f7d703f6">
But as long as update are also on Lemon Squeezy, this is ok I guess.
