### ISSUE TITLE
Feature Request: Add support for .DNG image files

### ISSUE THREAD

**Issue by naveen-bharathi** [dqhieu/CompressXApp#55]
When an image is AirDropped from an iPhone to a mac, it is sent as a .DNG file. Currently CompressX app does not recognise a .DNG image file.

**Comment by dqhieu** [comment]
Hi @naveen-bharathi , DNG is supported in this version. Please try it out and let me know if it works https://drive.google.com/file/d/1LPljHPv6DqihIAk6LASBYO3Dg87ELjlc/view?usp=sharing

**Comment by naveen-bharathi** [comment]
Thanks for addressing this request, @dqhieu. The app now accepts DNG images. However, when I try to compress a DNG image, the process simply stops midway without any error message.

**Comment by dqhieu** [comment]
Hi @naveen-bharathi , does it happen for the version above?

**Comment by naveen-bharathi** [comment]
@dqhieu, the version from Google Drive works fine. I thought it was the same as the one I currently have installed, as the version numbers were the same.

**Comment by dqhieu** [comment]
Thanks for confirming. This is pre-release that will be rolled out in the next few days. Feel free to let me know if you have any other issue
