### ISSUE TITLE
keep audio lossless

### ISSUE THREAD

**Issue by ihubgit** [dqhieu/CompressXApp#59]
Hi while there's a way to toggle video quality and output, this is lacking for audio : it only exports to lossy vorbis, resulting in noticeable loss in quality.
It would be nice to be able to toggle audio quality and output too, and to be able to have a passthrough option.

**Comment by dqhieu** [comment]
Hi @ihubgit , this issue is now fixed in the latest version 1.9. You can download it at https://compressx.app/latest or just update your current app

**Comment by ihubgit** [comment]
Hi just got the latest version and i'm unable to see where i can toggle this option. It's not in the preferences, nor in the main window when dropping a file. Audio is still being automatically transcoded to Vorbis.
Can you tell me how i can keep my lossless Wav format ?
